### PR TITLE
Added BetaGeoBetaBinom data gen

### PR DESCRIPTION
**Pull request by zscore**
No testing yet but integrated into fitter function. Code for https://github.com/CamDavidsonPilon/lifetimes/issues/171

### CODE REVIEW

**Comment by zscore** [comment]
fyi the build failed because of it was unable to download some index files. don't know if there's anything to be fixed there.

**Comment by CamDavidsonPilon** [comment]
Ah, it's an unrelated problem. Please ignore. Are you able to add a test in `test_estimation` for this too?

**Comment by zscore** [comment]
I can write tests for the data generation method, although I do not see any tests currently written for it. Is it enough to just do a sanity check and look at some bounds?

**Comment by zscore** [comment]
also, this build is failing because of a different commit you merged in, right?

**Pull request closed without merging**
