### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by praneethkumarpidugu**

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
:+1: thanks @praneethkumarpidugu!

**Comment by praneethkumarpidugu** [comment]
No problem!
I'm trying to finish my school by using your library.
Also, Is there a place where I could get very recent chunks of open data
related to ecommerce for playing around the lifetime
 ?

On Wed, Jan 6, 2016 at 7:33 PM, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> [image: :+1:] thanks @praneethkumarpidugu
> <https://github.com/praneethkumarpidugu>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/lifetimes/pull/35#issuecomment-169509300>
> .
>



-- 

*Praneeth*
*Application Developer Intern*
Wind River Systems
*Masters of Science in computer science*
Lakehead University
*Honours in computer and electrical engineering*,
University of Windsor
*cellphone contact*: *+1-226-345-4245*
*office contact:* *+1-613-963-1344*
*office email*:
*Praneeth.Pidugu@windriver.com <Praneeth.Pidugu@windriver.com>*
*personal email*:*pidugu2007@gmail.com <pidugu2007@gmail.com>*

**Comment by CamDavidsonPilon** [comment]
Unfortunately not that I've seen. the cd-now dataset is the most popular (and possibly only)

**Comment by praneethkumarpidugu** [comment]
hmm...May be I will try to parse through the data and change it here and
there :D

On Wed, Jan 6, 2016 at 7:48 PM, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> Unfortunately not that I've seen. the cd-now dataset is the most popular
> (and possibly only)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/lifetimes/pull/35#issuecomment-169511349>
> .
>



-- 

*Praneeth*
*Application Developer Intern*
Wind River Systems
*Masters of Science in computer science*
Lakehead University
*Honours in computer and electrical engineering*,
University of Windsor
*cellphone contact*: *+1-226-345-4245*
*office contact:* *+1-613-963-1344*
*office email*:
*Praneeth.Pidugu@windriver.com <Praneeth.Pidugu@windriver.com>*
*personal email*:*pidugu2007@gmail.com <pidugu2007@gmail.com>*

**Pull request merged**
