### PR TITLE
Fix loading model for __dict__ attribute

### PR DESCRIPTION
**Pull request by aprotopopov**
Now all attributes should be available [example](https://stackoverflow.com/a/25128214/4542359). Feel free to add new tests or ideas how to test saving/loading models

### CODE REVIEW

**Comment by aprotopopov** [comment]
Also added ability to add custom index for `fit` methods. It could be useful for saving model and loading it, when index could be your custom id's.

**Comment by aprotopopov** [comment]
And one more commit to whether save data from fitter or not, because in my case it's about 15mln and then dill object is about 750Mb... Mostly from `data` field

**Comment by aprotopopov** [comment]
Autopep8 was done. Also add F401 and E501 for Makefile for `flake8` to pass `make autolint` command.

**Comment by CamDavidsonPilon** [comment]
In the `fit` methods, can you add docs for what the `index` kwarg does / should be?

**Comment by aprotopopov** [comment]
Yeah, sure. Forgot about that. Is it clearer now?

**Comment by CamDavidsonPilon** [comment]
lgtm, thanks!

**Pull request merged**
