### PR TITLE
Beta Geo Fitter with Time-Invariant Covariates. Unit tests.

### PR DESCRIPTION
**Pull request by meremeev**
Issue #331 Extend BG/NBD model with Time-Invariant Covariates

### CODE REVIEW

**Comment by psygo** [comment]
I don't know if I'm competent enough for this. So I'm passing the ball to @aprotopopov and @CamDavidsonPilon, let's see if they know how to deal with this model properly.

**Comment by marcusinthesky** [comment]
Are there any updated on when this might be merged?

**Comment by meremeev** [comment]
Well, this PR is 2 years old. Looks like there is no interest in this functionality.

**Comment by juanitorduz** [comment]
This would be a great nice addition 🚀 !

**Comment by CamDavidsonPilon** [comment]
Hey, this won't be added, unfortunately. Another developer needs to take over this project (either a fork or a change of maintainer) for new feature additions.

**Comment by ColtAllen** [comment]
@meremeev @juanitorduz @tamirbennatan This PR has been recreated and merged in the [ `lifetimes` fork](https://github.com/ColtAllen/lifetimes/tree/main) I've created.

**Pull request closed without merging**
