### PR TITLE
Fixed periodicity in rfm utils

### PR DESCRIPTION
**Pull request by NudnikShpilkis**
I've written some changes to the following functions to better align them with the suspected bugs per #280 and #281:

- `calibration_and_holdout_data`: I've added variables to count the first-period transactions, calculate recency for discrete time models (as per https://github.com/CamDavidsonPilon/lifetimes/issues/280#issuecomment-505526696).  I'm not convinced that counting the first-period transactions follows the literature, however, we can let users decide what they'd prefer.  I've added an additional variable to let the user calculate recency as a discrete measure for use in the BG/BB (as per http://www.brucehardie.com/notes/010/).  I've also separated out the operations to generate holdout data into its own function for better testing and model validation.

- `summary_data_from_transaction_data`: Grouping is now done by `customer_id_col` and a special Pandas grouper based on the user-defined frequency.  The function takes the same additional inputs that `calibration_and_holdout_data` takes.

- `expected_cumulative_transactions`: The dates and summed aggregated transactions are now calculated correctly using the `freq` and start date.

`beta_geo_beta_binomial`: Updated `fit` function as per https://github.com/CamDavidsonPilon/lifetimes/issues/259#issuecomment-480820040.  Additionally aliased `predict` function as `conditional_expected_number_of_purchases_up_to_time` to make the fitter compatible with a few more plotting functions.

I've added the following functions:

- `holdout_data`: I've split off the holdout data calculations from `calibration_and_holdout_data` into their own function.  I found it easier to have a smaller function to calculate the holdout data for model validation.
- `plot_calibration_purchases_vs_holdout_spend`: Almost identical to `plot_calibration_purchases_vs_holdout_purchases`.  The Y-axis plots the CLV instead of purchases in the holdout period.  An example of this plot can be seen in http://www.brucehardie.com/papers/020/fader_et_al_mksc_10.pdf.

I have not yet written the unit tests for these changes, but I wanted to give others the opportunity to view these changes and comment.

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Thoughtful additions, thanks! 

There are a number of files under `lifetimes/.ipynb_checkpoints` that shouldn't be there. Can those be removed from the PR please?

**Comment by isaachaberman** [comment]
Will do!  

I'm also working through the tests now to make sure all the changes are up to snuff.

**Comment by isaachaberman** [comment]
@CamDavidsonPilon How should we treat `observation_period_end` in the utils functions.  If we treat it as the specific day itself regardless of the period we'll be more exacting.  However, our calculations for T will not be integers.  If we treat it as a period, our results will be less exacting and T will always be an integer. 

Here's a short example exploring the differences:

```python
import numpy as np
import pandas as pd

observation_period_end = "2015-02-07"
calibration_end = "2015-02-01"
freq, freq_multiplier = "W", 1

#With periods
(pd.to_datetime(today).to_period('W') - pd.to_datetime(calibration_end).to_period('W')).n
1

#With exact dates
(pd.to_datetime(today) - pd.to_datetime(calibration_end)) / np.timedelta64(1, freq) / freq_multiplier
0.8571428571428571

```

**Comment by CamDavidsonPilon** [comment]
No reason for T to be an integer (do you agree?). I'm happy with the former.

**Comment by isaachaberman** [comment]
I prefer the former as well as it keeps to a stricter definition of periods.

**Comment by isaachaberman** [comment]
I've added a few more functions to plot the cumulative and incremental CLV.  To do so, I added some new utils functions including a `customer_lifetime_value` function that should work with any `freq` not just months.  Let me know what you think.

**Comment by isaachaberman** [comment]
I've added one new function `plot_cumulative_clv_from_t_cal` which lets you plot cumulative clv from the end of the calibration period.  It uses `expected_cumulative_clv` and `customer_lifetime_value` as the other cumulative CLV functions do, but requires the user to enter the calibration period ending and a starting CLV value for all customers.

**Comment by psygo** [comment]
So... again, I haven't had much time lately, but I'm going to do my best to schedule one or two days next week to incorporate the PR queue into the `dev` branch at least.

But, in order to ease our lives &mdash; maybe one day you will review my PRs also &mdash;, I would ask you (@isaachaberman) to do some things for me:

1. Getting the `.ipynb_checkpoints/` folders out of the way by adding them to the `.gitignore` file, as they are mostly Jupyter logs.
    - You can get them in every possible folders all at once by doing something like `**/.ipynb_checkpoints` I think.
1. I have been thinking about adding a `benchmarks` folder to the library where we would store scripts that demonstrate a bug or show how to use some special function, etc.
    - You could then put one for the bug(s) you found in there.
1. Create a separate PR for the fixes or modifications of the `plotting` functions. This would ease the life of whoever is trying to review the code.

If you're enthusiastic about this library, I would for sure welcome you to the team as a new collaborator &mdash; I'm a new member as well. You would only need the @CamDavidsonPilon's permission. The next thing/issue I really think (I) should be taken care of are the *convergence errors* and how to deal with the *negative log special cases*, if you can take a look at them, it would be very valuable.

**Pull request closed without merging**
