### PR TITLE
Small safety check on inputs to fitters.

### PR DESCRIPTION
**Pull request by statwonk**
Still a bit of a python noob, so forgive me if this is a bit pedantic --- getting up to speed with `lifetimes` and python. :)

Similar to the issue here, https://github.com/CamDavidsonPilon/lifetimes/issues/67 `observation_period_end` was confusing to me (until I read its definition 😛 !). I kept fumbling with it and hitting a deep `numpy` error caused by div by 0 [here](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L290).

This check would have alerted me, that's all. :) Hoping to spend some time learning BTYD over the next couple of months!

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Hey @statwonk! Hm, if you are hitting the error here: https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L290, then is your entire `T` column all zeros? I don't see how that could be 0 otherwise.

**Comment by statwonk** [comment]
Hey @CamDavidsonPilon! The gist is that I was using `lifetimes` in an engineering context where the series was a span of two hours contained within a single day. I set the `observation_period_end` simply to the date like `2017-07-13` without realizing it'd truncate. I'm not sure how many people this fix'll help, but I figured it couldn't hurt and wanted to dip my toe into contributing some python code. :)

Hopefully more to come!

**Comment by CamDavidsonPilon** [comment]
hm, so aside from being confused by `observation_period_end`, was the problem also that the default `freq` was in days? (and it sounds like all your data was from the current day, hence `max(T) == 0`).

**Comment by statwonk** [comment]
I went back and tried to create a minimally reproducible example. I found that `age` was an empty `numpy` array rather than 0: `array([], dtype=float64)`.

Here's the example,

data: https://gist.github.com/statwonk/61ad1f6fff454dcd8a11b49632701a17
script (run from `/lifetimes/lifetimes/`): https://gist.github.com/statwonk/b93947b101308c0d2d94ade2216ab506

Here's the stacktrace,

```
2017-07-19 01:02:03.601827 # <--- min time
2017-07-19 17:19:08.323395 # <--- max time
```

```python
Traceback (most recent call last):
  File "inserter_p_alive.py", line 19, in <module>
    bgf.fit(summary['frequency'], summary['recency'], summary['T'])
  File "/Users/statwonk/Library/Python/2.7/lib/python/site-packages/lifetimes/fitters/beta_geo_fitter.py", line 79, in fit
    self._scale = _scale_time(T)
  File "/Users/statwonk/Library/Python/2.7/lib/python/site-packages/lifetimes/utils.py", line 290, in _scale_time
    return 10. / age.max()
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by CamDavidsonPilon** [comment]
Okay, I see the problem now. Thanks for taking the time to explain it 👍

**Pull request merged**
