### PR TITLE
Typo Fix in Doc: From Lifelines to Lifetimes

### PR DESCRIPTION
**Pull request by keshavramaswamy**
Fixed a typo in the documentation.

### CODE REVIEW

**Comment by keshavramaswamy** [comment]
@CamDavidsonPilon  May I know why the CI build passed for one version - Python 3.3 and failed for the rest?

**Comment by CamDavidsonPilon** [comment]
hm, looks like it has to do with a pandas error. Investigating.

**Comment by CamDavidsonPilon** [comment]
I've pushed a fix, but this change is independent of it, and is 👍 

Merging. Thanks for the contribution!

**Comment by keshavramaswamy** [comment]
Thanks @CamDavidsonPilon!

**Pull request merged**
