### PR TITLE
Better Docstrings for the (some) Fitters

### PR DESCRIPTION
**Pull request by psygo**
The modified files are the *BG/NBD*, *Pareto/NBD* and *Gamma-Gamma* fitters. I've also added some stuff to the `utils.py` file.

The intention behind this pull request is essentially to add mentions to the equations behind some methods and functions. However, I've also reformatted some of the code, nothing beyond superficial tabs and line brakes and spacings to add a bit more consistency to the files.

If this is formatting is welcome, I could do it for the rest of the code base; else, I can revert what I changed and submit only the docstring improvements.

I intend on fixing some minor docstring (and hard coding) issues I've also seen in the `plotting.py` file next, so please let me know if I should keep going or simply stop.

### CODE REVIEW

**Comment by psygo** [comment]
Btw, I still haven't understood why is it that you're importing `matplotlib.pyplot` in every function instead of at the top of the file. Is it because you didn't want to import it when the file is imported because it's a big library?

**Comment by psygo** [comment]
Take a look at the [related plot *PR*](https://github.com/CamDavidsonPilon/lifetimes/pull/291).

**Comment by CamDavidsonPilon** [comment]
> Btw, I still haven't understood why is it that you're importing matplotlib.pyplot in every function instead of at the top of the file. Is it because you didn't want to import it when the file is imported because it's a big library?

I think it's to make matplotlib an optional dependency. I think, however, it's popular enough that we can probably promote it to a required dependency.

**Comment by CamDavidsonPilon** [comment]
> I intend on fixing some minor docstring (and hard coding) issues I've also seen in the plotting.py file next, so please let me know if I should keep going or simply stop.

Please continue, these are helpful additions

**Pull request merged**
